name: (disabled) Legacy Pages deploy

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pages deploy via Actions disabled; site deploys from branch settings."
